default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development

test:
  <<: *default
  database: db/test

production:
  <<: *default
  database: db/production
